<a href="https://colab.research.google.com/github/Sim8n88/ml_projects/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
obroty = np.array([1200, 3400, 2100, 5600, 1900])
koszty = np.array([800, 2000, 1500, 4000, 1200])
suma=np.sum(obroty)
print(suma)
srednia=np.mean(obroty)
print(srednia)
min=np.min(koszty)
max=np.max(koszty)
print(min)
print(max)
czysty_zysk=koszty-obroty
print(czysty_zysk)
max_ruch=np.argmax(obroty)
print(max_ruch)
pom=np.arange(1,13)
tab=np.reshape(pom,(3,4))
suma_kol_1=np.sum(tab,axis=0)
print(suma_kol_1)
max_wiersz=np.max(tab,axis=1)
print(max_wiersz)

14200
2840.0
800
4000
[ -400 -1400  -600 -1600  -700]
3
[15 18 21 24]
[ 4  8 12]
