<a href="https://colab.research.google.com/github/Sim8n88/ml_projects/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
liczby=np.arange(50,61)
print(liczby)
print(liczby[3])
print(liczby[2:6])
liczby2=np.arange(1,13)
print(liczby2)
liczby2reshape=liczby2.reshape(4,3)
print(liczby2reshape)
print(liczby2reshape[2,1])
zarobki = np.array([3500, 7200, 4100, 9500, 2800])
dobrze_platne=zarobki[zarobki>=5000]
print(dobrze_platne)
liczby88=np.arange(1,21)
liczby_parzyste=liczby88[liczby88%2==0]
print(liczby_parzyste)
wiek = np.array([14, 22, 17, 30, 45, 19, 12])
pelnoletni_i_mniej_niz_30=wiek[(wiek>=18)&(wiek<30)]
print(pelnoletni_i_mniej_niz_30)

[50 51 52 53 54 55 56 57 58 59 60]
53
[52 53 54 55]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
[7200 9500]
[ 2  4  6  8 10 12 14 16 18 20]
[22 19]
