<a href="https://colab.research.google.com/github/Sim8n88/ml_projects/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
tab=[1,2,3,4]
num_tab=np.array(tab)
num_tab2=np.array([1,2,3,4,5])
num_tab22=num_tab2+100
print(num_tab)
print(num_tab22)
kwadrat=num_tab2**2
print(kwadrat)
macierz=np.array([[2,4,1,8],[24,8,5,6]])
print(macierz)

losowe=np.arange(1,20,2)
print(losowe)
zera=np.zeros((3,3))
print(zera)
losowe=np.random.rand(5)
print(losowe)
ceny = np.array([100, 200, 300])
ceny_po_znizce=ceny*0.8
print(ceny_po_znizce)

[1 2 3 4]
[101 102 103 104 105]
[ 1  4  9 16 25]
[[ 2  4  1  8]
 [24  8  5  6]]
[ 1  3  5  7  9 11 13 15 17 19]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.0855846  0.36226585 0.94775971 0.17265278 0.18325553]
[ 80. 160. 240.]
